### ISSUE TITLE
Window size of output window is too big

### ISSUE THREAD

**Issue by sam6134** [gishi523/semantic-stixels#3]
The code is compiling fine on my system but the only problem is the window size of the output is too big thus all the four images are not visible on the whole screen. 
Also the window is not resizing I tried moving the cursor but it does not resize.
Could you help me with this issue?

**Comment by gishi523** [comment]
Hi, @sam6134 

To resize window, you can adjust `drawSize` [here](https://github.com/gishi523/semantic-stixels/blob/master/main.cpp#L381).

For example, this is half size of current setting.
```
const cv::Size drawSize = cv::Size(disparity.cols / 2, disparity.rows / 2);
```

Or,  using `cv::namedWindow` and  `cv::WINDOW_NORMAL`  enables resizing window by cursor.

```diff
 	cv::Mat legend;
 	drawLegend(legend, classes, colors);
 
+	cv::namedWindow("Semantic Stixels Demo", cv::WINDOW_NORMAL);
+
 	for (int frameno = 0;; frameno++)
 	{
 		cap1 >> I1;
```

Regards,
Gishi

**Comment by sam6134** [comment]
Thanks a lot that works.
Regards
Samarth
